[package]
description = "Excel Toolbox"
edition = '2021'
license = "Apache-2.0"
name = 'xltool'
publish = true
version = '0.0.0'

[dependencies]
calamine = '0.26'
comfy-table = '7.1'
crossterm = '0.28'
ratatui = '0.29'
serde_json = '1.0'
tui-input = '0.11'
unicode-width = '0.2'
unidecode = '0.3'
